name: Publish

on:
  push:
    paths:
      - 'code/**'
    branches: [ main ]

jobs:
  publish:
    name: Publish
    uses: Flaminel/universal-workflows/.github/workflows/dotnet.build.nuget.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
    secrets: inherit